### ISSUE TITLE
Algorithm final round

### ISSUE THREAD

**Issue by NNoMatchFound** [sbrodehl/HashCode#3]
Guten Abend, können Sie mir bitte den Algorithmus Ihrer letzten Aufgabenlösung über einen Router beschreiben?

**Comment by sbrodehl** [comment]
We implemented various methods using different approaches and performance metrics, take a closer look at the `place_*` methods to see the details.
I can briefly describe the goals of each approach:
* `place_routers_on_skeleton`
Computes the skeleton of the available space ("rooms") and places router on it. Precalculates the available routers and used budget.

* `place_routers_on_skeleton_iterative`
Same as `place_routers_on_skeleton`, but places router iteratively on randomized positions on the skeleton.

* `place_routers_randomized`
Places routers iteratively on uniform sampled positions, updates used cables by computing a mst or via bsf to the closest places cable.

* `place_routers_randomized_by_score`
Same as `place_routers_randomized`, but chooses a position based on the approximated score of that position.

* `place_routers_by_convolution`
Computes scores of router position by convolving the available space with a constant squared matrix with size `radius x radius`. As a result of this, routers can 'see' through walls, which does not comply with the problem statement.

**Comment by NNoMatchFound** [comment]
Thank you!
